AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prodect-management
  Sample SAM Template for prodect-management

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Parameters:
  BrevoApiKey:
    Type: String
    Description: "BREVO API Key"
  jwtSecret:
    Type: String
    Description: "JWT Secret Key"
  rzpKeyId:
    Type: String
    Description: "Razorpay Key ID"
  rzpKeySecret:
    Type: String
    Description: "Razorpay Key Secret"

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/Auth/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Timeout: 10
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Environment:
        Variables:
          USERS_TABLE: !Ref AuthTable
          JWT_SECRET: !Ref jwtSecret
          JWT_ALGO: HS256
          ACCESS_TOKEN_DAYS: "1"
          REFRESH_TOKEN_DAYS: "7"
          MAX_OTP_PER_HOUR: "5"
      Events:
        AuthEvent:
          Type: Api
          Properties:
            Path: /auth/{proxy+}
            Method: any
        AddressEvent:
          Type: Api
          Properties:
            Path: /user/{proxy+}
            Method: any

  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: auth
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true  

  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/Products/
      Timeout: 10
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
      Events:
        OrderPlacedListener:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ecommerce.orders"
              detail-type:
                - "OrderPlaced"
        ProductsApiRoot:
          Type: Api
          Properties:
            Path: /products
            Method: any
        ProductsApiProxy:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: any
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products_v2
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
        - AttributeName: entity_type
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: requested_by
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
        - AttributeName: entity_type
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: category_index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: requested_by_index
          KeySchema:
            - AttributeName: requested_by
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: false

  CartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/Cart/
      Timeout: 10
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref CartTable
      Environment:
        Variables:
          CARTS_TABLE: !Ref CartTable
      Events:
        OrderPlacedListener:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ecommerce.orders"
              detail-type:
                - "OrderPlaced"
        CartApiRoot:
          Type: Api
          Properties:
            Path: /cart
            Method: any
        CartApiProxy:
          Type: Api
          Properties:
            Path: /cart/{proxy+}
            Method: any

  CartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: carts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cart_id
          AttributeType: S
        - AttributeName: entity_type
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: cart_id
          KeyType: HASH
        - AttributeName: entity_type
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user_id_index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: entity_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/Orders/
      Timeout: 10
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - Statement:
          - Effect: Allow
            Action: events:PutEvents
            Resource: "*"
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
          RAZORPAY_API_KEY: !Ref rzpKeyId
          RAZORPAY_API_SECRET: !Ref rzpKeySecret
      Events:
        OrdersApiRoot:
          Type: Api
          Properties:
            Path: /orders
            Method: any
        OrdersApiProxy:
          Type: Api
          Properties:
            Path: /orders/{proxy+}
            Method: any
        OrderPlacedListener:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ecommerce.orders"
              detail-type:
                - "OrderPlaced"

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: orders
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user_id_index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  HistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/History/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref HistoryTable
      Environment:
        Variables:
          HISTORY_TABLE: !Ref HistoryTable
      Events:
        OrderPlacedListener:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ecommerce.orders"
              detail-type:
                - "OrderPlaced"
        HistoryEvent:
          Type: Api
          Properties:
            Path: /history/{proxy+}
            Method: any

  HistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: history
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: user_id_index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false

  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/Email/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Architectures:
      - x86_64
      Environment:
        Variables:
          BREVO_URL: https://api.brevo.com/v3/smtp/email
          BREVO_API_KEY: !Ref BrevoApiKey
          DEFAULT_SENDER: Support Team <QwK5g@example.com>
          DEFAULT_EMAIL: kohlicriss@gmail.com

          TRACK_ORDER_LINK: https://store.anasol.co.in/track-order
          LOGO_URL: https://www.anasol.co.in/assets/Logo1-BPHJw_VO.png
      Events:
        OrderPlacedListener:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ecommerce.orders"
              detail-type:
                - "OrderPlaced"
        EmailEvent:
          Type: Api
          Properties:
            Path: /email/{proxy+}
            Method: any


  BannersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: banners
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true  


  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: prodect-management-app-files
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
              - Content-Length
            MaxAge: 3000

  FilesFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: services/Files/
        Handler: lambda_handler.lambda_handler
        Runtime: python3.12
        Timeout: 10
        Architectures:
          - x86_64
        Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BannersTable

        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::${FilesBucket}/*'

        Environment:
          Variables:
            # FIXED: Changed from S3_REGION and S3_BUCKET to match python code
            FILES_REGION: ap-south-1
            FILES_BUCKET: !Ref FilesBucket
            BANNERS_TABLE: !Ref BannersTable

        Events:
          FilesEvent:
            Type: Api
            Properties:
              Path: /file/{proxy+}
              Method: any
          BannersAdminEvent:
            Type: Api
            Properties:
              Path: /banner/admin/{proxy+}
              Method: any
          BannersPublicEvent:
            Type: Api
            Properties:
              Path: /banner/public/{proxy+}
              Method: any

Outputs:
  ApiBaseUrl:
    Description: Base URL for API Gateway
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  AuthTableName:
    Description: Auth users DynamoDB table
    Value: !Ref AuthTable

  ProductsTableName:
    Description: Products DynamoDB table
    Value: !Ref ProductsTable

  OrdersTableName:
    Description: Orders DynamoDB table
    Value: !Ref OrdersTable

  HistoryTableName:
    Description: History DynamoDB table
    Value: !Ref HistoryTable

  FilesBucketName:
    Description: S3 bucket for file storage
    Value: !Ref FilesBucket

  FilesBucketArn:
    Description: ARN of the files S3 bucket
    Value: !GetAtt FilesBucket.Arn
    
  CartTableName:
      Description: Carts DynamoDB table
      Value: !Ref CartTable